{{- $cloud := include "ap.cloud" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ap.fullname" . }}-api
  labels:
    {{- include "ap.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  annotations:
    {{- if eq $cloud "gcp" }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- if .Values.gcp.backendConfig.enabled }}
    cloud.google.com/backend-config: {{ printf "{\"default\": \"%s-api\"}" (include "ap.fullname" .) | squote }}
    {{- end }}
    {{- end }}
    {{- with .Values.api.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "ap.selectorLabels" (dict "ctx" $ "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
