{{- if and .Values.worker.enabled .Values.worker.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ap.fullname" . }}-worker
  labels:
    {{- include "ap.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "ap.selectorLabels" (dict "ctx" $ "component" "worker") | nindent 6 }}
{{- end }}
