// Ablation harness for the event-analysis scorer — Phase B of
// docs/rectification-and-event-analysis.md.
//
//   npx tsx scripts/ablation.ts
//
// The question this answers is "does each scoring layer earn its place?", and
// the honest difficulty is that there is no ground truth to measure accuracy
// against (see Part 5 of the research: no licence-clean source of real birth
// times exists). So it measures four things that do not need ground truth:
//
//   A  Fire rate       — how often the layer contributes anything at all.
//   B  Rank influence  — how often removing it changes the percentile a user
//                        would see. A layer that never changes a conclusion is
//                        decoration, however sound its astrology.
//   C  Redundancy      — correlation with the other layers. A layer that only
//                        fires when another already has is echoing, not adding.
//   D  Identifiability — the one that matters for rectification. Hold a birth
//                        time as truth, generate events the model calls strongly
//                        indicated at that time, then scan all 1440 minutes of
//                        the day and see whether the scan finds its way back.
//                        Ablate a layer and see whether recovery gets worse.
//
// D is circular by construction: events generated by the model are recovered by
// the model. That makes it a test of IDENTIFIABILITY — does this layer carry
// birth-time information — and not of whether the astrology is true. Nothing
// here can test the latter.

import { computeChart } from "../src/astro/engine";
import { detectYogas } from "../src/astro/yogas";
import {
  analyseEvent,
  scoreEventDate,
  dashaTreeFor,
  LifeEventInput,
  LayerSwitches,
  ReasonLayer,
} from "../src/astro/eventAnalysis";
import { EVENT_KARAKAS } from "../src/astro/eventKaraka";
import { BirthData } from "../src/astro/types";

const LAYERS: ReasonLayer[] = ["dasha", "boundary", "transit", "varga", "yoga"];
const DAY_MS = 86_400_000;

const BASE: BirthData = {
  name: "Subject", year: 1985, month: 6, day: 12,
  hour: 10, minute: 30, second: 0,
  tzOffsetHours: 5.5, latitude: 17.385, longitude: 78.4867,
  placeLabel: "Hyderabad",
};

/** A spread of charts across decades, latitudes and times of day. */
function chartFor(i: number) {
  return computeChart({
    ...BASE,
    year: 1945 + ((i * 7) % 60),
    month: 1 + ((i * 3) % 12),
    day: 1 + ((i * 11) % 28),
    hour: (i * 13) % 24,
    minute: (i * 29) % 60,
    latitude: 8 + ((i * 3) % 45),
    longitude: -100 + ((i * 17) % 200),
  });
}

function without(layer: ReasonLayer): LayerSwitches {
  return { [layer]: false };
}
function only(layer: ReasonLayer): LayerSwitches {
  return Object.fromEntries(LAYERS.map((l) => [l, l === layer])) as LayerSwitches;
}

const mean = (x: number[]) => (x.length ? x.reduce((s, v) => s + v, 0) / x.length : 0);
const pct = (n: number, d: number) => (d ? ((n / d) * 100).toFixed(1) : "0.0");

function corr(a: number[], b: number[]): number {
  const ma = mean(a), mb = mean(b);
  let num = 0, da = 0, db = 0;
  for (let i = 0; i < a.length; i++) {
    num += (a[i] - ma) * (b[i] - mb);
    da += (a[i] - ma) ** 2;
    db += (b[i] - mb) ** 2;
  }
  return da && db ? num / Math.sqrt(da * db) : 0;
}

// ── A, B, C ────────────────────────────────────────────────────────────────

function contributionStudy(samples: number) {
  console.log(`\n═══ A/B/C — layer contribution over ${samples} (chart, event, date) triples ═══\n`);

  const contrib: Record<ReasonLayer, number[]> = {
    dasha: [], boundary: [], transit: [], varga: [], yoga: [],
  };
  const rankDelta: Record<ReasonLayer, number[]> = {
    dasha: [], boundary: [], transit: [], varga: [], yoga: [],
  };
  const totals: number[] = [];

  for (let i = 0; i < samples; i++) {
    const chart = chartFor(i);
    const dashas = dashaTreeFor(chart);
    const yogas = detectYogas(chart);
    const k = EVENT_KARAKAS[i % EVENT_KARAKAS.length];
    const birth = Date.UTC(chart.birth.year, chart.birth.month - 1, chart.birth.day);
    const date = new Date(birth + (((i * 37) % 1000) / 1000) * (Date.now() - birth));
    const ev: LifeEventInput = { type: k.id, date, precision: "month", confidence: "sure" };

    const full = scoreEventDate(chart, ev, { dashas, yogas });
    totals.push(full);

    const basePct = analyseEvent(chart, ev, { dashas, yogas, nullSamples: 60 }).percentile;

    for (const l of LAYERS) {
      // Marginal contribution: what the total loses when this layer goes.
      contrib[l].push(full - scoreEventDate(chart, ev, { dashas, yogas, layers: without(l) }));
      // Does removing it move the number a user actually sees?
      const p = analyseEvent(chart, ev, { dashas, yogas, nullSamples: 60, layers: without(l) }).percentile;
      if (basePct !== null && p !== null) rankDelta[l].push(Math.abs(p - basePct));
    }
  }

  console.log(`  mean total score: ${mean(totals).toFixed(1)}\n`);
  console.log("  layer      fires   mean pts   share    |Δpercentile|   never changes rank");
  console.log("  ────────────────────────────────────────────────────────────────────────");
  for (const l of LAYERS) {
    const fired = contrib[l].filter((v) => v > 0.05);
    const inert = rankDelta[l].filter((v) => v === 0).length;
    console.log(
      `  ${l.padEnd(9)} ${pct(fired.length, contrib[l].length).padStart(5)}%  ` +
      `${(fired.length ? mean(fired) : 0).toFixed(1).padStart(8)}   ` +
      `${pct(contrib[l].reduce((s, v) => s + v, 0), totals.reduce((s, v) => s + v, 0)).padStart(5)}%   ` +
      `${mean(rankDelta[l]).toFixed(1).padStart(11)}     ` +
      `${pct(inert, rankDelta[l].length).padStart(5)}%`,
    );
  }

  console.log("\n  C — redundancy (correlation of marginal contributions):");
  for (let a = 0; a < LAYERS.length; a++) {
    for (let b = a + 1; b < LAYERS.length; b++) {
      const r = corr(contrib[LAYERS[a]], contrib[LAYERS[b]]);
      if (Math.abs(r) >= 0.3) {
        console.log(`    ${LAYERS[a]} ↔ ${LAYERS[b]}: r = ${r.toFixed(2)}`);
      }
    }
  }
}

// ── D — identifiability ────────────────────────────────────────────────────

/** Sum the score of every event for a candidate birth minute. */
function scanScore(base: BirthData, minute: number, events: LifeEventInput[], layers?: LayerSwitches): number {
  const chart = computeChart({ ...base, hour: Math.floor(minute / 60), minute: minute % 60, second: 0 });
  const dashas = dashaTreeFor(chart);
  const yogas = detectYogas(chart);
  let total = 0;
  for (const e of events) total += scoreEventDate(chart, e, { dashas, yogas, layers });
  return total;
}

/**
 * Events the model calls strongly indicated at the true birth time — the
 * synthetic stand-in for a user who reports real, well-dated events.
 */
function generateEvents(
  base: BirthData,
  trueMinute: number,
  count: number,
  jitterDays = 0,
  seed = 1,
): LifeEventInput[] {
  const chart = computeChart({ ...base, hour: Math.floor(trueMinute / 60), minute: trueMinute % 60, second: 0 });
  const dashas = dashaTreeFor(chart);
  const yogas = detectYogas(chart);
  const birth = Date.UTC(base.year, base.month - 1, base.day);
  const out: LifeEventInput[] = [];

  for (let n = 0; n < count; n++) {
    const k = EVENT_KARAKAS[(n * 5) % EVENT_KARAKAS.length];
    let best: { date: Date; score: number } | null = null;
    // Search adulthood in ten-day steps for the date this chart likes most.
    for (let age = 18 * 365; age < 60 * 365; age += 10) {
      const date = new Date(birth + age * DAY_MS);
      const s = scoreEventDate(chart, { type: k.id, date, precision: "exact", confidence: "sure" }, { dashas, yogas });
      if (!best || s > best.score) best = { date, score: s };
    }
    if (best) {
      // Real users do not report the date this chart likes best — they report
      // the date something actually happened, which sits near that optimum at
      // best, and which they may misremember. Without this jitter the study is
      // recovering the model's own argmax and flatters itself badly.
      const wobble = jitterDays
        ? Math.round((((seed * 9301 + n * 49297) % 233280) / 233280 - 0.5) * 2 * jitterDays)
        : 0;
      out.push({
        type: k.id,
        date: new Date(best.date.getTime() + wobble * DAY_MS),
        precision: jitterDays > 45 ? "year" : jitterDays > 0 ? "month" : "exact",
        confidence: "sure",
      });
    }
  }
  return out;
}

function identifiabilityStudy(subjects: number, eventsPer: number, stepMinutes: number) {
  console.log(`\n═══ D — identifiability: ${subjects} subjects × ${eventsPer} events, ${stepMinutes}-min scan ═══`);
  console.log("    (circular by construction — measures whether a layer carries");
  console.log("     birth-time information, NOT whether the astrology is true)\n");

  const configs: Array<{ name: string; layers?: LayerSwitches }> = [
    { name: "all layers" },
    ...LAYERS.map((l) => ({ name: `without ${l}`, layers: without(l) })),
    ...LAYERS.map((l) => ({ name: `only ${l}`, layers: only(l) })),
  ];
  const errors: Record<string, number[]> = Object.fromEntries(configs.map((c) => [c.name, []]));
  // How wide the winning plateau is — for rectification this IS the window a
  // user should be shown, so a layer that flattens the curve is actively bad.
  const plateau: Record<string, number[]> = Object.fromEntries(configs.map((c) => [c.name, []]));

  for (let i = 0; i < subjects; i++) {
    const base: BirthData = {
      ...BASE,
      year: 1950 + ((i * 11) % 55),
      month: 1 + ((i * 5) % 12),
      day: 1 + ((i * 13) % 28),
      latitude: 8 + ((i * 7) % 45),
      longitude: -80 + ((i * 23) % 160),
    };
    const trueMinute = (i * 97) % 1440;
    const events = generateEvents(base, trueMinute, eventsPer);

    for (const cfg of configs) {
      // Score the whole day, then take the winning PLATEAU rather than the
      // first argmax. A layer that barely varies with birth time produces a
      // nearly flat curve, and `s > best` would hand it minute 0 every time —
      // which reads as a systematic error rather than the "this layer knows
      // nothing" it actually is.
      const scores: number[] = [];
      for (let m = 0; m < 1440; m += stepMinutes) scores.push(scanScore(base, m, events, cfg.layers));
      const top = Math.max(...scores);
      const winners: number[] = [];
      for (let i = 0; i < scores.length; i++) {
        if (scores[i] >= top - 1e-9) winners.push(i * stepMinutes);
      }
      const estimate = winners[Math.floor(winners.length / 2)];
      const raw = Math.abs(estimate - trueMinute);
      // Circular error — 23:58 is two minutes from 00:00, not 1438.
      errors[cfg.name].push(Math.min(raw, 1440 - raw));
      plateau[cfg.name].push(winners.length * stepMinutes);
    }
  }

  const median = (x: number[]) => {
    const s = [...x].sort((a, b) => a - b);
    return s[Math.floor(s.length / 2)];
  };
  const within = (x: number[], m: number) => pct(x.filter((v) => v <= m).length, x.length);

  console.log("  config           median err   mean err   ≤60min   ≤120min   plateau   (chance: 360m / 8.3% / 16.7%)");
  console.log("  ────────────────────────────────────────────────────────────────────────────────────────────────");
  for (const cfg of configs) {
    const e = errors[cfg.name];
    console.log(
      `  ${cfg.name.padEnd(15)} ${String(median(e)).padStart(9)}m ${mean(e).toFixed(0).padStart(10)}m  ` +
      `${within(e, 60).padStart(6)}%  ${within(e, 120).padStart(7)}%  ` +
      `${median(plateau[cfg.name]).toFixed(0).padStart(6)}m`,
    );
  }
}

/**
 * How many events does a user actually have to supply? Directly product-facing:
 * it decides what the rectification flow asks for before it will show anything.
 */
function eventCountStudy(subjects: number, counts: number[], stepMinutes: number, jitterDays: number) {
  console.log(
    `\n═══ E — recovery vs number of events (${subjects} subjects, dasha+boundary, ` +
    `±${jitterDays}d date noise) ═══\n`,
  );
  const layers: LayerSwitches = { transit: false, varga: false, yoga: false };
  const median = (x: number[]) => [...x].sort((a, b) => a - b)[Math.floor(x.length / 2)];

  console.log("  events   median err   ≤30min   ≤120min   median plateau");
  console.log("  ────────────────────────────────────────────────────────");
  for (const n of counts) {
    const errs: number[] = [];
    const plats: number[] = [];
    for (let i = 0; i < subjects; i++) {
      const base: BirthData = {
        ...BASE,
        year: 1950 + ((i * 11) % 55), month: 1 + ((i * 5) % 12), day: 1 + ((i * 13) % 28),
        latitude: 8 + ((i * 7) % 45), longitude: -80 + ((i * 23) % 160),
      };
      const trueMinute = (i * 97) % 1440;
      const events = generateEvents(base, trueMinute, n, jitterDays, i + 1);
      const scores: number[] = [];
      for (let m = 0; m < 1440; m += stepMinutes) scores.push(scanScore(base, m, events, layers));
      const top = Math.max(...scores);
      const winners: number[] = [];
      for (let j = 0; j < scores.length; j++) if (scores[j] >= top - 1e-9) winners.push(j * stepMinutes);
      const est = winners[Math.floor(winners.length / 2)];
      const raw = Math.abs(est - trueMinute);
      errs.push(Math.min(raw, 1440 - raw));
      plats.push(winners.length * stepMinutes);
    }
    const within = (m: number) => pct(errs.filter((v) => v <= m).length, errs.length);
    console.log(
      `  ${String(n).padStart(6)}   ${String(median(errs)).padStart(9)}m  ${within(30).padStart(6)}%  ` +
      `${within(120).padStart(7)}%   ${String(median(plats)).padStart(12)}m`,
    );
  }
}

/**
 * How much date error can the method absorb? This is the number that bounds
 * what may honestly be promised: the drift table in Part 1 says every dasha
 * boundary moves 1.35–4.5 days per minute of birth time, so a user who is a
 * month out on a date cannot expect better than tens of minutes back.
 */
function noiseStudy(subjects: number, jitters: number[], stepMinutes: number) {
  console.log(`\n═══ F — recovery vs date accuracy (${subjects} subjects, 5 events, dasha+boundary) ═══\n`);
  const layers: LayerSwitches = { transit: false, varga: false, yoga: false };
  const median = (x: number[]) => [...x].sort((a, b) => a - b)[Math.floor(x.length / 2)];

  console.log("  date error   median birth-time err   ≤30min   ≤120min");
  console.log("  ──────────────────────────────────────────────────────");
  for (const j of jitters) {
    const errs: number[] = [];
    for (let i = 0; i < subjects; i++) {
      const base: BirthData = {
        ...BASE,
        year: 1950 + ((i * 11) % 55), month: 1 + ((i * 5) % 12), day: 1 + ((i * 13) % 28),
        latitude: 8 + ((i * 7) % 45), longitude: -80 + ((i * 23) % 160),
      };
      const trueMinute = (i * 97) % 1440;
      const events = generateEvents(base, trueMinute, 5, j, i + 1);
      const scores: number[] = [];
      for (let m = 0; m < 1440; m += stepMinutes) scores.push(scanScore(base, m, events, layers));
      const top = Math.max(...scores);
      const winners: number[] = [];
      for (let k2 = 0; k2 < scores.length; k2++) if (scores[k2] >= top - 1e-9) winners.push(k2 * stepMinutes);
      const est = winners[Math.floor(winners.length / 2)];
      const raw = Math.abs(est - trueMinute);
      errs.push(Math.min(raw, 1440 - raw));
    }
    const within = (m: number) => pct(errs.filter((v) => v <= m).length, errs.length);
    console.log(
      `  ${(j === 0 ? "exact" : `±${j}d`).padStart(10)}   ${String(median(errs)).padStart(20)}m  ` +
      `${within(30).padStart(6)}%  ${within(120).padStart(7)}%`,
    );
  }
}

const t0 = Date.now();
contributionStudy(150);
identifiabilityStudy(30, 5, 4);
eventCountStudy(20, [1, 2, 3, 5, 8], 4, 20);
noiseStudy(20, [0, 7, 20, 45, 90], 4);
console.log(`\nTotal: ${((Date.now() - t0) / 1000).toFixed(1)}s\n`);
